var constants = {

    Product: "product",
    Home: "home",
    User: "user",
    Buzz: "buzz",
    Category: "category",
    Review: "review",
    Comment: "comment",
    Contact: "contact",
    Vendor: "vendor",
    Image: "image",
    Products: "products",
    Homes: "homes",
    Users: "users",
    Buzzes: "buzzes",
    Categories: "categories",
    Reviews: "reviews",
    Comments: "comments",
    Vendors: "vendors",
    Images: "images",
    Created: "created",
    Updated: "updated",
    Deleted: "deleted",
    Uploaded: "uploaded",
    Email: "email",
    Id: "_id",
    Collection: "collection",
    BAD_REQUEST_ERROR: "Bad Request",
    CONFLICT_ERROR: "Conflict",
    INTERNAL_SERVER_ERROR: "Internal Server Error",
    NOT_FOUND_ERROR: "Not Found",
    UNAUTHORISED_ERROR: "UnAuthorised",
    OK_STATUS: "OK",
    EMAIL_PATTERN: /^.*@.*\..*/,
    HTTP_POST: "POST",
    HTTP_PUT: "PUT",
    HTTP_GET: "GET",
    HTTP_DELETE: "DELETE"
};

module.exports = constants;
